name: Cypress CI
on: [push]
jobs:
   cypress-run:
     runs-on: ubuntu-latest
     defaults:
       run:
         working-directory: ./app
     steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Install dependencies
          run: npm install
        - name: Cypress.io
          uses: cypress-io/github-action@v6
          with:
             working-directory: ./app
